trigger:
- main
- qa

pool:
  vmImage: ubuntu-latest

variables:
  node_version: '20.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js app'

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: |
      .next/**
      public/**
      server.js
      next.config.js
      package.json
      node_modules/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy app files to staging'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/nextjs-app.zip'
    replaceExistingArchive: true
  displayName: 'Zip the app'

- publish: '$(Build.ArtifactStagingDirectory)/nextjs-app.zip'
  artifact: drop
